MODEL:
  META_ARCHITECTURE: "CenterNetDetector"
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  BACKBONE:
    NAME: "MY_build_dla_backbone"
  WEIGHTS: "models/CenterNet2_DLA-BiFPN-P3_4x.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  DLA:
    NUM_LAYERS: 34
    NORM: "BN"
  CENTERNET:  
    IN_FEATURES: ["dla5"]
    POST_NMS_TOPK_TEST: 128
    FPN_STRIDES: [32]
    SOI: [[0, 10000000]]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
# DATASETS:
#   TRAIN: ("voc_2012_trainval",)
#   TEST: ("voc_2012_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 2000
  WARMUP_ITERS: 4000
  WARMUP_FACTOR: 0.00025
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 900
  MAX_SIZE_TEST: 736
  MIN_SIZE_TEST: 512
  CUSTOM_AUG: 'EfficientDetResizeCrop'
OUTPUT_DIR: "./output-MY-BiFPN"
