MODEL:
  META_ARCHITECTURE: "CenterNetDetector"
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  BACKBONE:
    # NAME: "MY_build_p35_fcos_dla_bifpn_attention_backbone"
    NAME: "MY_build_resnet_bifpn_backbone_attention"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  WEIGHTS: "models/CenterNet2_X101-DCN_2x.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  CENTERNET:  
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    POST_NMS_TOPK_TEST: 128
    FPN_STRIDES: [8, 16, 32, 64, 128]
    SOI: [[0, 80], [64, 160], [128, 320], [256, 640], [512, 10000000]]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
# DATASETS:
#   TRAIN: ("voc_2012_trainval",)
#   TEST: ("voc_2012_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 2000
  WARMUP_ITERS: 4000
  WARMUP_FACTOR: 0.00025
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 900
  MAX_SIZE_TEST: 736
  MIN_SIZE_TEST: 512
  CUSTOM_AUG: 'EfficientDetResizeCrop'
OUTPUT_DIR: "./output-MY-BiFPN-X101"
