_BASE_: "Base-CenterNet2.yaml"
MODEL:
  PROPOSAL_GENERATOR:
    NAME: "MY_ATSSModule"
  BACKBONE:
    NAME: "MY_build_p37_fcos_dla_bifpn_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  CENTERNET:
    POST_NMS_TOPK_TEST: 128
  ATSS:
    ANCHOR_SIZES: (64, 128, 256, 512, 1024) # 8S
    ASPECT_RATIOS: (0.5,1.0,2.0,)
    SCALES_PER_OCTAVE: 1
    USE_DCN_IN_TOWER: False
    POSITIVE_TYPE: 'ATSS' # how to select positves: ATSS (Ours) , SSC (FCOS), IoU (RetinaNet)
    TOPK: 9 # topk for selecting candidate positive samples from each level
    REGRESSION_TYPE: 'BOX' # regressing from a 'BOX' or a 'POINT'
  WEIGHTS: ''
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 360000
  BASE_LR: 0.08
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 90000
TEST:
  EVAL_PERIOD: 7500
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 900
