_BASE_: "../Base-CenterNet2.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "MY_build_p37_fcos_dla_bifpn_pan_cbam_backbone"
  PROPOSAL_GENERATOR:
    NAME: "MY_GFLModule"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  DLA:
    NUM_LAYERS: 34
    # NORM: "SyncBN"
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
  CENTERNET:
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    POST_NMS_TOPK_TEST: 128
    FPN_STRIDES: [8, 16, 32, 64, 128]
    SOI: [[0, 80], [64, 160], [128, 320], [256, 640], [512, 10000000]]
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (300000, 340000)
  MAX_ITER: 360000
  CHECKPOINT_PERIOD: 50000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_ITERS: 4000
  WARMUP_FACTOR: 0.00025
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 900
  MAX_SIZE_TEST: 736
  MIN_SIZE_TEST: 512
  CUSTOM_AUG: MY_AUG